import { useEffect } from 'react';

const Privacy = () => {
  useEffect(() => {
    document.title = 'Privacy Policy | EventBuddy AI';
  }, []);

  return (
    <div className="min-h-screen bg-gradient-to-br from-purple-50 to-indigo-100 py-12 px-4">
      <div className="max-w-4xl mx-auto">
        <div className="bg-white rounded-xl shadow-lg p-8">
          <h1 className="text-3xl font-bold text-gray-900 mb-2">Privacy Policy</h1>
          <p className="text-gray-600 mb-8">
            Effective date: {new Date().toISOString().slice(0, 10)}
          </p>

          <div className="prose prose-lg max-w-none">
            <p className="text-gray-700 mb-6">
              This Privacy Policy describes how EventBuddy AI ("we", "our", or "us") collects, uses,
              and safeguards information when you use our website and the EventBuddy Discord application.
              We only describe behaviors present in this codebase and the documented integrations.
            </p>

            <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">1. What information we collect</h2>
            <p className="text-gray-700 mb-4">Depending on how you use EventBuddy, we may process:</p>
            <ul className="list-disc pl-6 mb-6 text-gray-700 space-y-2">
              <li>
                <strong>Discord identifiers</strong>: server (guild) ID, channel ID, message ID, and the Discord user ID
                and username of message authors. These are required to operate features in Discord.
              </li>
              <li>
                <strong>Message content</strong>: messages posted in channels where the bot is active may be
                logged to provide AI responses and analytics. The codebase includes utilities that can store
                message content and AI responses in a database for context and analytics.
              </li>
              <li>
                <strong>Event data</strong>: event name, date/time, status and related metadata created by server
                administrators via slash commands.
              </li>
              <li>
                <strong>CSV attendee data (optional)</strong>: if a server admin uploads a CSV to import attendees,
                we may store fields such as attendee name, email, Discord handle/ID and optional additional columns
                contained in the CSV. Uploading this data is optional and controlled by the admin.
              </li>
              <li>
                <strong>Channel metadata and preferences</strong>: channel names/purpose and per-user preferences that
                help tailor responses and context.
              </li>
              <li>
                <strong>Technical data</strong>: basic diagnostics and timestamps generated by the application and
                database (e.g., created_at/updated_at).
              </li>
            </ul>

            <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">2. How we use information</h2>
            <ul className="list-disc pl-6 mb-6 text-gray-700 space-y-2">
              <li>Operate the EventBuddy Discord bot and features (slash commands, channel utilities).</li>
              <li>Generate responses with AI and improve conversation quality and relevance.</li>
              <li>Provide event and community analytics to server admins.</li>
              <li>Maintain safety, reliability and troubleshooting of the service.</li>
            </ul>

            <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">3. AI processing</h2>
            <p className="text-gray-700 mb-6">
              EventBuddy integrates with Google Generative AI to produce responses. When the bot needs an AI reply,
              relevant context (such as recent messages, channel metadata and user preferences) may be sent to the AI
              provider solely to generate the response. We do not sell your data.
            </p>

            <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">4. Legal bases</h2>
            <ul className="list-disc pl-6 mb-6 text-gray-700 space-y-2">
              <li><strong>Contract/necessity</strong>: to provide the features you request in Discord.</li>
              <li><strong>Legitimate interests</strong>: to keep the service secure, reliable and useful.</li>
              <li><strong>Consent</strong>: for optional features such as attendee CSV uploads by admins.</li>
            </ul>

            <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">5. Data sharing</h2>
            <ul className="list-disc pl-6 mb-6 text-gray-700 space-y-2">
              <li><strong>Supabase</strong> is used for hosting our Postgres database and APIs.</li>
              <li><strong>Discord</strong> provides the platform and APIs where the bot operates.</li>
              <li><strong>Google Generative AI</strong> is used to generate AI responses from provided context.</li>
              <li>We do not sell personal data. We may disclose information if required by law or to protect users.</li>
            </ul>

            <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">6. Retention</h2>
            <p className="text-gray-700 mb-6">
              Records are retained for as long as needed to operate the service. Conversation logs associated with
              archived events may be cleaned up after approximately 90 days based on the included cleanup routines.
              Admins can request deletion of specific records subject to platform constraints.
            </p>

            <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">7. Security</h2>
            <p className="text-gray-700 mb-6">
              We use industry-standard safeguards provided by our infrastructure providers (e.g., Supabase) and
              limit permissions to what the bot requires. No method of transmission or storage is 100% secure.
            </p>

            <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">8. Children</h2>
            <p className="text-gray-700 mb-6">
              EventBuddy is not directed to children under 13. Do not use the service if you are under the minimum
              digital consent age in your region.
            </p>

            <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">9. Your choices and rights</h2>
            <ul className="list-disc pl-6 mb-6 text-gray-700 space-y-2">
              <li>Server admins can remove the bot, revoke permissions, or request deletion of specific data.</li>
              <li>You may request access or deletion of data that relates to you by contacting the admin of the
              server where the bot is installed or by contacting us directly.</li>
            </ul>

            <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">10. Contact</h2>
            <p className="text-gray-700 mb-6">
              For privacy inquiries, contact: <strong>amaobiokeoma@gmail.com</strong>.
            </p>

            <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">11. Changes to this policy</h2>
            <p className="text-gray-700 mb-6">We may update this policy. We will post the updated date at the top of this page.</p>
          </div>

          <div className="mt-8 pt-6 border-t border-gray-200">
            <a 
              href="/" 
              className="inline-flex items-center text-purple-600 hover:text-purple-700 font-medium"
            >
              ← Back to home
            </a>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Privacy;
