// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tvewdfvhlvlflpqanora.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2ZXdkZnZobHZsZmxwcWFub3JhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NTI1NzUsImV4cCI6MjA3MDIyODU3NX0.8LZYYutb0uzKCF0PmzmZeCa3AMnQdo1FCARh85Ricv4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});