// Discord Bot Prompts - Centralized prompts for EventBuddy
import { ENHANCED_DISCORD_BOT_PROMPTS } from './enhanced-discord-bot-prompts';

export const DISCORD_BOT_PROMPTS = {
  // Enhanced System prompt for natural language processing
  SYSTEM_PROMPT: ENHANCED_DISCORD_BOT_PROMPTS.SYSTEM_PROMPT,

  // Enhanced response when user lacks permissions for slash commands
  PERMISSION_DENIED: ENHANCED_DISCORD_BOT_PROMPTS.PERMISSION_DENIED,

  // Enhanced help message for regular users (non-owners)
  USER_HELP: ENHANCED_DISCORD_BOT_PROMPTS.USER_HELP,

  // Enhanced help message for server owners
  OWNER_HELP: ENHANCED_DISCORD_BOT_PROMPTS.OWNER_HELP,

  // Enhanced channel creation success message
  CHANNEL_CREATED: ENHANCED_DISCORD_BOT_PROMPTS.CHANNEL_CREATED,

  // Enhanced event check responses
  NO_ACTIVE_EVENTS: ENHANCED_DISCORD_BOT_PROMPTS.NO_ACTIVE_EVENTS,
  
  ACTIVE_EVENTS_FOUND: ENHANCED_DISCORD_BOT_PROMPTS.ACTIVE_EVENTS_FOUND,

  // Enhanced error messages
  ERROR_GENERIC: ENHANCED_DISCORD_BOT_PROMPTS.ERROR_GENERIC,
  ERROR_CHANNEL_CREATE: ENHANCED_DISCORD_BOT_PROMPTS.ERROR_CHANNEL_CREATE,
  ERROR_DATABASE: ENHANCED_DISCORD_BOT_PROMPTS.ERROR_DATABASE,

  // Additional enhanced messages
  WELCOME_MESSAGE: ENHANCED_DISCORD_BOT_PROMPTS.WELCOME_MESSAGE,
  INTELLIGENT_FILTERING_ACTIVE: ENHANCED_DISCORD_BOT_PROMPTS.INTELLIGENT_FILTERING_ACTIVE,
  ANALYTICS_OVERVIEW: ENHANCED_DISCORD_BOT_PROMPTS.ANALYTICS_OVERVIEW,
  SECURITY_ALERT: ENHANCED_DISCORD_BOT_PROMPTS.SECURITY_ALERT,
  CULTURAL_ADAPTATION: ENHANCED_DISCORD_BOT_PROMPTS.CULTURAL_ADAPTATION,
};